version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: ./.docker/dockerfiles/dev.backend.dockerfile
    environment:
      - APP_ENV=local
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    depends_on:
      - database
    networks:
      - subs
      
  frontend:
    build:
      context: ./
      dockerfile: ./.docker/dockerfiles/dev.frontend.dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - nginx
    ports:
      - 3000:3000
    networks:
      - subs

  nginx:
    build:
      context: ./
      dockerfile: ./.docker/dockerfiles/nginx.dockerfile
    depends_on:
      - backend
    ports:
      - 80:8080
    networks:
      - subs

  database:
    image: mariadb:10.8-jammy
    volumes: 
      - database:/var/lib/mysql
    environment:
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    networks:
      - subs

volumes:
  database:

networks:
  subs:
    driver: bridge